services:
  postgres:
    image: 'postgres:latest'
    environment:
      - 'POSTGRES_DB=hotel_db'
      - 'POSTGRES_PASSWORD=1234'
      - 'POSTGRES_USER=user1'
    ports:
      - '5432'

  pgadmin:
    image : 'dpage/pgadmin4:latest'
    environment:
      PGADMIN_DEFAULT_EMAIL: hicham.win@gmail.com
      PGADMIN_DEFAULT_PASSWORD: 1234
      PGADMIN_LISTEN_PORT: 5051
    ports:
      - '5051:5051'
